# Password validation
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 100

# Username validation
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 50

# Token expiration (in minutes)
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 30

# Rate limiting
MAX_LOGIN_ATTEMPTS = 5
LOGIN_COOLDOWN_MINUTES = 15
