name: Slack Webhook Test

on:
  workflow_dispatch:

jobs:
  send-test-message:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Send Slack Test Message
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":tada: *Slack webhook test successful!*"
                }
              }
            ]
          }' \
          "${{ secrets.SLACK_WEBHOOK }}"
